name: Generate Gallery JSON
on:
  push:
    paths:
      - 'photos/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Tento řádek explicitně vynutí právo na zápis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Aktualizováno na nejnovější verzi v4

      - name: Generate JSON Matrix
        run: |
          echo "Generuji seznam souborů..."
          find photos -type f ! -name ".*" | sort | awk 'BEGIN {print "["} {print "  \"" $0 "\","} END {print "]"}' > gallery.json
          sed -i '$x;s/,\n]$/\n]/;p;x' gallery.json
          cat gallery.json

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Předání tokenu pro ověření identity bota
        run: |
          git config --global user.name "Gallery Bot"
          git config --global user.email "bot@github.com"
          git add gallery.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizace galerií" && git push)
